/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sabrina Zakir (https://sketchfab.com/sabrinazakir123)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cute-pug-waffles-39890591e199490c9a81a2360a68c1a7
title: Cute Pug Waffles
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ArObj(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cute_pug_waffles/scene.gltf')

  // useFrame(() => {
  //   gl.setRenderTarget(target)
  //   gl.render(scene, cam.current)
  //   gl.setRenderTarget(null)

  // })
  return (
    <group ref={group} {...props} position={props.pos} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.material_14} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.material_13} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.material_12} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.material_11} />
        <mesh geometry={nodes.mesh_4.geometry} material={materials.material_10} />
        <mesh geometry={nodes.mesh_5.geometry} material={materials.material_9} />
        <mesh geometry={nodes.mesh_6.geometry} material={materials.material_8} />
        <mesh geometry={nodes.mesh_7.geometry} material={materials.material_7} />
        <mesh geometry={nodes.mesh_8.geometry} material={materials.material_6} />
        <mesh geometry={nodes.mesh_9.geometry} material={materials.material_5} />
        <mesh geometry={nodes.mesh_10.geometry} material={materials.material_4} />
        <mesh geometry={nodes.mesh_11.geometry} material={materials.material_4} />
        <mesh geometry={nodes.mesh_12.geometry} material={materials.defaultMat_0} />
        <mesh geometry={nodes.mesh_13.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.mesh_14.geometry} material={materials.material_3} />
        <mesh geometry={nodes.mesh_15.geometry} material={materials.material_2} />
        <mesh geometry={nodes.mesh_16.geometry} material={materials.material_1} />
        <mesh geometry={nodes.mesh_17.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/cute_pug_waffles/scene.gltf')
